### ISSUE TITLE
Найти задачи

### ISSUE THREAD

**Issue by da-the-dev** [da-the-dev/transportation_problem#1]
Нужно найти задачи на Transportation, решить и решение сюда скинуть

**Comment by KhairullinaAlsu** [comment]
https://cbom.atozmath.com/example/CBOM/Transportation.aspx?q=ram&q1=E1
Здесь подробное решение задачи с помощью Russell's Approximation Method

**Comment by KhairullinaAlsu** [comment]
https://cbom.atozmath.com/example/CBOM/Transportation.aspx?q=vam&q1=E1
Vogel's method

**Comment by KhairullinaAlsu** [comment]
https://cbom.atozmath.com/example/CBOM/Transportation.aspx?q=nwcm&q1=E1
North-West corner method
